import "./globals.css";
import { TodosProvider } from "@/store/todos";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TodosProvider>{children}</TodosProvider>
        <Footer/>
      </body>
    </html>
  );
}
